CUDA_VISIBLE_DEVICES=0 python main.py \
    -dataset camrest \
    -run_type train \
    -add_additional_loss \
    -act \
    -st \
    -sc \
    -rk \
    -model_dir camrest \
    -epochs 30 \
    -batch_size 8\
    -warmup_ratio 0.1\
    -max_to_keep_ckpt 20 \
